version: '3'
services:

  pandoc:
    build:
      context: .
      dockerfile: Dockerfile
    image: novarx/pandoc
    container_name: pandoc
    tty: true
    volumes:
      - data:/data

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './'
